name: RingLauncher
options:
  bundleIdPrefix: com.yourname
targets:
  RingLauncher:
    type: application
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: RingLauncher  # 它会自动递归寻找 App, Managers, Views 等子目录
    settings:
      # 指定 Info.plist 的路径（假设你放在 Resources 下或者根目录）
      INFOPLIST_FILE: RingLauncher/Resources/Info.plist 
      CODE_SIGNING_ALLOWED: NO
      # 如果你有图标，可以在 Assets.xcassets 里创建一个名为 AppIcon 的项
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon