name: RingLauncher
options:
  bundleIdPrefix: com.ring.launcher
targets:
  RingLauncher:
    type: application
    platform: macOS
    deploymentTarget: "13.0"
    sources: 
      - path: RingLauncher
    settings:
      INFOPLIST_FILE: RingLauncher/Resources/Info.plist
      CODE_SIGNING_ALLOWED: NO