name: RingLauncher
options:
  bundleIdPrefix: com.ring.launcher
targets:
  RingLauncher:
    type: application
    platform: macOS
    deploymentTarget: "13.0"
    sources: 
      - path: RingLauncher
    settings:
      # 显式指定 Bundle Identifier
      PRODUCT_BUNDLE_IDENTIFIER: com.ring.launcher.RingLauncher
      # 显式指定版本号
      MARKETING_VERSION: 1.0.0
      CURRENT_PROJECT_VERSION: 1
      INFOPLIST_FILE: RingLauncher/Resources/Info.plist
      CODE_SIGNING_ALLOWED: NO
